name: build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-front-end:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - uses: davidB/rust-cargo-make@v1
      - name: Build
        run: |
          cargo make --cwd ./website build
