name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - uses: davidB/rust-cargo-make@v1
      - name: Build
        run: |
          cargo make --cwd ./website export
          cargo make --cwd ./website install
          rm ./website/static/.gitignore

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/static
